import { Matter, MatterDocument, TimelineEvent, Reminder } from '../types';

export const INITIAL_MATTERS: Matter[] = [
  {
    id: 'matter_e968_2022',
    suitNumber: 'E/968/2022',
    title: 'Chisom vs. Mr. Ibe Christian Aforka',
    court: 'High Court 3, Enugu Division',
    judge: 'Hon. Justice Ajah',
    plot: 'S/10 Plot 33, Independence Layout',
    plaintiffs: ['Chisom Legal Chambers (Claimant)'],
    defendants: ['Mr. Ibe Christian Aforka'],
    leadLawyer: 'lawyer_chisom',
    leadLawyerName: 'Barr. Chisom Okeke',
    teamMembers: ['lawyer_chisom', 'admin_demo', 'paralegal_joy', 'client_ibe'],
    status: 'active',
    filingDate: '2022-04-12',
    nextHearingDate: '2026-10-26',
    purpose: 'P.T.C',
    appearances: 'Chisom Esq. for Claimant, N.O. Egwu Esq. for Defendant',
    summaryNotes: 'Land ownership dispute over S/10 Plot 33. Pre-trial conference scheduled for document exchange and issues formulation.',
    createdBy: 'admin_demo',
    createdByName: 'Admin Partner',
    createdAt: new Date('2022-04-12').toISOString(),
    updatedAt: new Date('2026-08-01').toISOString(),
  },
  {
    id: 'matter_e779_2021',
    suitNumber: 'E/779/2021',
    title: 'State vs. Theodore Anyanwu',
    court: 'High Court 3, Enugu Division',
    judge: 'Hon. Justice Ajah',
    plot: 'Plot 73, Trans-Ekulu',
    plaintiffs: ['The State (Attorney General)'],
    defendants: ['Theodore Anyanwu'],
    leadLawyer: 'lawyer_chisom',
    leadLawyerName: 'Barr. Chisom Okeke',
    teamMembers: ['lawyer_chisom', 'admin_demo', 'paralegal_joy'],
    status: 'adjourned',
    filingDate: '2021-08-19',
    nextHearingDate: '2026-11-02',
    purpose: 'Hearing',
    appearances: 'Chisom Esq. for State, C.K. Okey Esq. for Defense',
    summaryNotes: 'Contempt of court and unlawful trespass hearing. Defense motion for extension of time granted on previous sitting.',
    createdBy: 'admin_demo',
    createdByName: 'Admin Partner',
    createdAt: new Date('2021-08-19').toISOString(),
    updatedAt: new Date('2026-08-05').toISOString(),
  },
  {
    id: 'matter_e357_2023',
    suitNumber: 'E/357/2023',
    title: 'Estate of Nnamani vs. Onyemuche Nnamani',
    court: 'High Court 3, Enugu Division',
    judge: 'Hon. Justice Ajah',
    plot: 'Commercial Bakery Plot, Ogui Road',
    plaintiffs: ['Elder Paul Nnamani (Administrator)'],
    defendants: ['Onyemuche Nnamani'],
    leadLawyer: 'lawyer_chisom',
    leadLawyerName: 'Barr. Chisom Okeke',
    teamMembers: ['lawyer_chisom', 'admin_demo'],
    status: 'active',
    filingDate: '2023-03-15',
    nextHearingDate: '2025-11-10',
    purpose: 'Mention',
    appearances: 'Chisom Esq. for Plaintiff',
    summaryNotes: 'Administration of estate and partition of bakery commercial building. Service of process confirmed on all parties.',
    createdBy: 'admin_demo',
    createdByName: 'Admin Partner',
    createdAt: new Date('2023-03-15').toISOString(),
    updatedAt: new Date('2026-07-20').toISOString(),
  },
  {
    id: 'matter_e569_2022',
    suitNumber: 'E/569/2022',
    title: 'Chukwuma vs. Dr. Ogbonna Chukwudi',
    court: 'High Court 3, Enugu Division',
    judge: 'Hon. Justice Ajah',
    plot: 'OS/1 Plot 9, GRA Enugu',
    plaintiffs: ['Chief E.A. Chukwuma'],
    defendants: ['Dr. Ogbonna Chukwudi'],
    leadLawyer: 'lawyer_chisom',
    leadLawyerName: 'Barr. Chisom Okeke',
    teamMembers: ['lawyer_chisom', 'admin_demo', 'paralegal_joy'],
    status: 'active',
    filingDate: '2022-11-04',
    nextHearingDate: '2026-09-22',
    purpose: 'Further Mention',
    appearances: 'Chisom Esq., U.B. Ani Esq.',
    summaryNotes: 'Boundary adjustment and perpetual injunction regarding OS/1 Plot 9. Outstanding survey plan filing.',
    createdBy: 'admin_demo',
    createdByName: 'Admin Partner',
    createdAt: new Date('2022-11-04').toISOString(),
    updatedAt: new Date('2026-08-02').toISOString(),
  },
  {
    id: 'matter_e104_2024',
    suitNumber: 'E/104/2024',
    title: 'Lagos State Housing Auth vs. Apex Developers Ltd',
    court: 'Federal High Court, Lagos Division',
    judge: 'Hon. Justice B. O. Quadri',
    plot: 'Plot 14, Lekki Phase 1',
    plaintiffs: ['Lagos State Housing Authority'],
    defendants: ['Apex Developers Ltd', 'Managing Director'],
    leadLawyer: 'lawyer_chisom',
    leadLawyerName: 'Barr. Chisom Okeke',
    teamMembers: ['lawyer_chisom', 'admin_demo', 'paralegal_joy'],
    status: 'won',
    filingDate: '2024-01-10',
    nextHearingDate: '2026-08-28',
    purpose: 'Ruling on Injunction',
    appearances: 'Lead Counsel Chisom with Paralegal Joy',
    summaryNotes: 'Commercial lease enforcement. Final ruling granted in favor of plaintiff with damages awarded.',
    createdBy: 'admin_demo',
    createdByName: 'Admin Partner',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2026-08-08').toISOString(),
  }
];

export const INITIAL_TIMELINE_EVENTS: Record<string, TimelineEvent[]> = {
  matter_e968_2022: [
    {
      id: 'time_1',
      matterId: 'matter_e968_2022',
      date: '2022-04-12',
      type: 'filing',
      summary: 'Writ of Summons and Statement of Claim filed at the Registry.',
      createdBy: 'admin_demo',
      createdByName: 'Admin Partner',
      createdAt: new Date('2022-04-12').toISOString(),
    },
    {
      id: 'time_2',
      matterId: 'matter_e968_2022',
      date: '2023-02-14',
      type: 'hearing',
      judge: 'Hon. Justice Ajah',
      purpose: 'Mention',
      appearances: 'Chisom Esq. for Claimant',
      summary: 'Matter mentioned for first time before Hon. Justice Ajah. Defendant served in court.',
      createdBy: 'lawyer_chisom',
      createdByName: 'Barr. Chisom Okeke',
      createdAt: new Date('2023-02-14').toISOString(),
    },
    {
      id: 'time_3',
      matterId: 'matter_e968_2022',
      date: '2026-05-18',
      type: 'ruling',
      judge: 'Hon. Justice Ajah',
      purpose: 'Ruling',
      appearances: 'Chisom Esq.',
      summary: 'Ruling delivered on Defendant motion to strike out paragraph 12. Motion dismissed with costs of N50,000.',
      createdBy: 'lawyer_chisom',
      createdByName: 'Barr. Chisom Okeke',
      createdAt: new Date('2026-05-18').toISOString(),
    }
  ]
};

export const INITIAL_DOCUMENTS: Record<string, MatterDocument[]> = {
  matter_e968_2022: [
    {
      id: 'doc_1',
      matterId: 'matter_e968_2022',
      fileName: 'Writ_of_Summons_E968_2022.pdf',
      storagePath: 'matters/matter_e968_2022/Writ_of_Summons.pdf',
      fileSize: 1048576,
      fileType: 'application/pdf',
      docType: 'pleading',
      uploadedBy: 'lawyer_chisom',
      uploadedByName: 'Barr. Chisom Okeke',
      uploadedAt: new Date('2022-04-12').toISOString(),
      version: 1,
      description: 'Original stamped Writ of Summons and Statement of Claim'
    },
    {
      id: 'doc_2',
      matterId: 'matter_e968_2022',
      fileName: 'Survey_Plan_Plot_33_Independence_Layout.pdf',
      storagePath: 'matters/matter_e968_2022/Survey_Plan.pdf',
      fileSize: 2097152,
      fileType: 'application/pdf',
      docType: 'exhibit',
      uploadedBy: 'paralegal_joy',
      uploadedByName: 'Joy Paralegal',
      uploadedAt: new Date('2022-05-01').toISOString(),
      version: 1,
      description: 'Certified True Copy of Surveyor General Plan No. EN/044/2020'
    }
  ]
};
