// Fictional demo data only - every name, suit number and address here is made up.
// Not imported by the app; kept as a reference for local testing.
import { Matter, MatterDocument, TimelineEvent, Reminder } from '../types';

export const INITIAL_MATTERS: Matter[] = [
  {
    id: 'matter_e968_2022',
    suitNumber: 'DEMO/968/2022',
    title: 'Demo Holdings Ltd vs. John Sample',
    court: 'Demo High Court, Division 1',
    judge: 'Hon. Justice Example',
    plot: 'Plot 1, Demo Estate',
    plaintiffs: ['Demo Holdings Ltd (Claimant)'],
    defendants: ['John Sample'],
    ownerId: 'demo_lawyer',
    ownerName: 'Demo Lawyer',
    members: { demo_lawyer: 'owner', admin_demo: 'editor', demo_paralegal: 'editor', demo_client: 'viewer' },
    status: 'active',
    filingDate: '2022-04-12',
    nextHearingDate: '2026-10-26',
    purpose: 'P.T.C',
    appearances: 'A. Demo Esq. for Claimant, B. Example Esq. for Defendant',
    summaryNotes: 'Land ownership dispute over Plot 1, Demo Estate. Pre-trial conference scheduled for document exchange and issues formulation.',
    createdBy: 'admin_demo',
    createdByName: 'Demo Admin',
    createdAt: new Date('2022-04-12').toISOString(),
    updatedAt: new Date('2026-08-01').toISOString(),
  },
  {
    id: 'matter_e779_2021',
    suitNumber: 'DEMO/779/2021',
    title: 'State vs. Jane Placeholder',
    court: 'Demo High Court, Division 1',
    judge: 'Hon. Justice Example',
    plot: 'Plot 2, Demo Estate',
    plaintiffs: ['The State (Attorney General)'],
    defendants: ['Jane Placeholder'],
    ownerId: 'demo_lawyer',
    ownerName: 'Demo Lawyer',
    members: { demo_lawyer: 'owner', admin_demo: 'editor', demo_paralegal: 'editor' },
    status: 'adjourned',
    filingDate: '2021-08-19',
    nextHearingDate: '2026-11-02',
    purpose: 'Hearing',
    appearances: 'A. Demo Esq. for State, C. Example Esq. for Defense',
    summaryNotes: 'Contempt of court and unlawful trespass hearing. Defense motion for extension of time granted on previous sitting.',
    createdBy: 'admin_demo',
    createdByName: 'Demo Admin',
    createdAt: new Date('2021-08-19').toISOString(),
    updatedAt: new Date('2026-08-05').toISOString(),
  },
  {
    id: 'matter_e357_2023',
    suitNumber: 'DEMO/357/2023',
    title: 'Estate of Sample vs. Alex Sample',
    court: 'Demo High Court, Division 1',
    judge: 'Hon. Justice Example',
    plot: 'Plot 3, Demo Estate',
    plaintiffs: ['Pat Sample (Administrator)'],
    defendants: ['Alex Sample'],
    ownerId: 'demo_lawyer',
    ownerName: 'Demo Lawyer',
    members: { demo_lawyer: 'owner', admin_demo: 'editor' },
    status: 'active',
    filingDate: '2023-03-15',
    nextHearingDate: '2025-11-10',
    purpose: 'Mention',
    appearances: 'A. Demo Esq. for Plaintiff',
    summaryNotes: 'Administration of estate and partition of bakery commercial building. Service of process confirmed on all parties.',
    createdBy: 'admin_demo',
    createdByName: 'Demo Admin',
    createdAt: new Date('2023-03-15').toISOString(),
    updatedAt: new Date('2026-07-20').toISOString(),
  },
  {
    id: 'matter_e569_2022',
    suitNumber: 'DEMO/569/2022',
    title: 'Example Farms vs. Dr. Sam Test',
    court: 'Demo High Court, Division 1',
    judge: 'Hon. Justice Example',
    plot: 'Plot 4, Demo Estate',
    plaintiffs: ['Example Farms Ltd'],
    defendants: ['Dr. Sam Test'],
    ownerId: 'demo_lawyer',
    ownerName: 'Demo Lawyer',
    members: { demo_lawyer: 'owner', admin_demo: 'editor', demo_paralegal: 'editor' },
    status: 'active',
    filingDate: '2022-11-04',
    nextHearingDate: '2026-09-22',
    purpose: 'Further Mention',
    appearances: 'A. Demo Esq., D. Example Esq.',
    summaryNotes: 'Boundary adjustment and perpetual injunction regarding Plot 4, Demo Estate. Outstanding survey plan filing.',
    createdBy: 'admin_demo',
    createdByName: 'Demo Admin',
    createdAt: new Date('2022-11-04').toISOString(),
    updatedAt: new Date('2026-08-02').toISOString(),
  },
  {
    id: 'matter_e104_2024',
    suitNumber: 'DEMO/104/2024',
    title: 'Demo State Housing Board vs. Sample Builders Ltd',
    court: 'Demo Federal High Court',
    judge: 'Hon. Justice Sample',
    plot: 'Plot 14, Lekki Phase 1',
    plaintiffs: ['Demo State Housing Board'],
    defendants: ['Sample Builders Ltd', 'Managing Director'],
    ownerId: 'demo_lawyer',
    ownerName: 'Demo Lawyer',
    members: { demo_lawyer: 'owner', admin_demo: 'editor', demo_paralegal: 'editor' },
    status: 'won',
    filingDate: '2024-01-10',
    nextHearingDate: '2026-08-28',
    purpose: 'Ruling on Injunction',
    appearances: 'A. Demo Esq. with Demo Paralegal',
    summaryNotes: 'Commercial lease enforcement. Final ruling granted in favor of plaintiff with damages awarded.',
    createdBy: 'admin_demo',
    createdByName: 'Demo Admin',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2026-08-08').toISOString(),
  }
];

export const INITIAL_TIMELINE_EVENTS: Record<string, TimelineEvent[]> = {
  matter_e968_2022: [
    {
      id: 'time_1',
      matterId: 'matter_e968_2022',
      date: '2022-04-12',
      type: 'filing',
      summary: 'Writ of Summons and Statement of Claim filed at the Registry.',
      createdBy: 'admin_demo',
      createdByName: 'Demo Admin',
      createdAt: new Date('2022-04-12').toISOString(),
    },
    {
      id: 'time_2',
      matterId: 'matter_e968_2022',
      date: '2023-02-14',
      type: 'hearing',
      judge: 'Hon. Justice Example',
      purpose: 'Mention',
      appearances: 'A. Demo Esq. for Claimant',
      summary: 'Matter mentioned for first time before Hon. Justice Example. Defendant served in court.',
      createdBy: 'demo_lawyer',
      createdByName: 'Demo Lawyer',
      createdAt: new Date('2023-02-14').toISOString(),
    },
    {
      id: 'time_3',
      matterId: 'matter_e968_2022',
      date: '2026-05-18',
      type: 'ruling',
      judge: 'Hon. Justice Example',
      purpose: 'Ruling',
      appearances: 'A. Demo Esq.',
      summary: 'Ruling delivered on Defendant motion to strike out paragraph 12. Motion dismissed with costs of N50,000.',
      createdBy: 'demo_lawyer',
      createdByName: 'Demo Lawyer',
      createdAt: new Date('2026-05-18').toISOString(),
    }
  ]
};

export const INITIAL_DOCUMENTS: Record<string, MatterDocument[]> = {
  matter_e968_2022: [
    {
      id: 'doc_1',
      matterId: 'matter_e968_2022',
      fileName: 'Writ_of_Summons_DEMO_968_2022.pdf',
      storagePath: 'matters/matter_e968_2022/Writ_of_Summons.pdf',
      downloadURL: '',
      fileSize: 1048576,
      fileType: 'application/pdf',
      docType: 'pleading',
      uploadedBy: 'demo_lawyer',
      uploadedByName: 'Demo Lawyer',
      uploadedAt: new Date('2022-04-12').toISOString(),
      version: 1,
      description: 'Original stamped Writ of Summons and Statement of Claim'
    },
    {
      id: 'doc_2',
      matterId: 'matter_e968_2022',
      fileName: 'Survey_Plan_Demo_Plot_1.pdf',
      storagePath: 'matters/matter_e968_2022/Survey_Plan.pdf',
      downloadURL: '',
      fileSize: 2097152,
      fileType: 'application/pdf',
      docType: 'exhibit',
      uploadedBy: 'demo_paralegal',
      uploadedByName: 'Demo Paralegal',
      uploadedAt: new Date('2022-05-01').toISOString(),
      version: 1,
      description: 'Certified True Copy of Surveyor General Plan No. DEMO/000/2020'
    }
  ]
};
